name: Semantic Release

on:
    workflow_dispatch:
    push:
        branches:
            - 'master'
jobs:
    build:
        # MUST CHANGE GITHUB_TOKEN PERMISSION FROM READ TO WRITE
        permissions: write-all
        strategy:
            matrix:
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install JDK
              uses: actions/setup-java@v3
              with:
                  java-version: 17
                  distribution: 'adopt'
                  cache: 'maven'

            - name: Run tests
              run: mvn clean test

            - name: Set up Node.js for Semantic Release
              uses: actions/setup-node@v2
              with:
                  node-version: 16

            - name: Sematic Release
              run: |
                  npm install -g @conveyal/maven-semantic-release semantic-release @semantic-release/changelog
                  semantic-release --prepare @conveyal/maven-semantic-release --publish @semantic-release/github --verify-conditions @semantic-release/github
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
