on:
    workflow_dispatch:
    push:
        branches:
            - 'master'
            
permissions:
  contents: write
  pull-requests: write

jobs:
    Release:
        # MUST CHANGE GITHUB_TOKEN PERMISSION FROM READ TO WRITE
        strategy:
            matrix:
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install Node for semantic-release
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - uses: google-github-actions/release-please-action@v3
              with:
                release-type: maven
                package-name: release-please-action
